services:
  - type: web
    name: sql-validator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: DB
          property: host
      - key: DB_PORT
        fromDatabase:
          name: DB
          property: port
      - key: DB_NAME
        fromDatabase:
          name: DB
          property: database
      - key: DB_USER
        fromDatabase:
          name: DB
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: DB
          property: password
